spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:mysql://localhost:3306/urbanaura_store_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    org.springframework.web: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        type:
          descriptor: TRACE
        SQL: OFF
      nodeValue: WARN
    blog: WARN

forex:
  api:
    key: "${FOREX_API_KEY:}"
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081
  ssl:
    client-auth:

api:
  prefix: /api/v1

auth:
  token:
    jwtSecret: "36763979244226452948404D635166546A576D5A7134743777217A25432A462D"
    expirationInMils: 3600000  # 1 hour in milliseconds

